#!/bin/bash
# Bash configuration file
# Alessandro Righi <alessandro.righi@alerighi.it>
# History:
#  - 2021-05-03 first version

# Setup $PATH
export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"

# GNU binaries for macOS
if [ "$(uname)" = "Darwin" ]; then
	export PATH="/usr/local/Cellar/coreutils/8.32/libexec/gnubin/:$PATH"
fi

# Android SDK
export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"

# set environment variables
export EDITOR=vim
export LANG="en_US.UTF-8"
export PS1="\[\e[32m\]\u\[\e[m\]\[\e[32m\]@\[\e[m\]\[\e[32m\]\h\[\e[m\] \[\e[34m\]\w\[\e[m\] \\$ "

# colors for less
export LESS_ADVANCED_PREPROCESSOR=1
export LESS="-R"
export LESS_TERMCAP_mb=$'\E[1;31m'
export LESS_TERMCAP_md=$'\E[1;36m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'

# useful aliases
alias ls='ls --color'
alias ll='ls -lhF'
alias la='ls -alhF'
alias grep='grep --color=always'
alias ..='cd ..'
